comment:
  layout: "header, diff, changes, uncovered, tree"
  behavior: default

coverage:
  status:
    project: on # default
    patch: off # SCSS files are in the patch but are never covered

# To Turn off comments completely:
# comment: false
