comment:
  layout: "header, diff, changes, uncovered, tree"
  behavior: default

# Ignore sass files so they do not affect the patch coverage
ignore:
  - "recipes/books/**/*"
  - "recipes/mixins/**/*"
  - "script/**/*"
  - "js/**/*"
  - "*"

# To Turn off comments completely:
# comment: false
