# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Set the formatter to 'stylish' From https://github.com/eslint/eslint/tree/master/lib/formatters
  formatter: stylish

# File Options
files:
  include: 'books/**/*.s+(a|c)ss'
  ignore:
    # This is here **ONLY** because :match("...") causes an unignorable failure
    - 'books/rulesets/mixins/_modify.scss'

# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq

  no-warn: 1
  no-debug: 1
  no-ids: 1 # This is only used for ToC nav element. TODO: Fix after https://github.com/sasstools/sass-lint/pull/677
  no-important: 2
  # hex-notation:
  #   - 2
  #   -
  #     style: uppercase
  indentation:
    - 2
    -
      size: 2
  property-sort-order:
    - 1
    -
      order:
        - display
        - margin
      ignore-custom-properties: true
  variable-for-property:
    - 2
    -
      properties:
        - margin
        # - content # Commented since easybake allows more stuff in the content()
