sudo: false
# Travis actually needs to have python, ruby, and nodejs installed.
# It _seems_ virtualenv is only available when the language is set to python
# When language=python it seems Travis runs this command:
# source ~/virtualenv/python2.7/bin/activate
language: python
python:
  - "2.7"

addons:
  apt:
    packages:
      # Used for the CNXML->HTML conversion
      - xsltproc

env:
- NODE_VERSION="6.9.1"

before_install:
  - nvm install $NODE_VERSION
  - rvm default
install:
  - ./script/setup
script: ./script/ci
after_success:
  # Report coverage to codecov
  - bash <(curl -s https://codecov.io/bash)
