version: '3.2'
services:
  fetch-html:
    build: .
    image: openstax/cnx-recipes
    environment:
      # This is necessary in order to mount the correct directory if we start
      # sibling containers
      HOST_PWD: "${PWD}"
      OUTPUT_DIR: /out
      BOOTSTRAP_ALREADY_RAN: 1
    volumes:
      - .:/code
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: /code/script/fetch-html

  neb:
    build: https://github.com/openstax/nebuchadnezzar.git
    image: openstax/nebuchadnezzar:latest
    environment:
      NEB_CONFIG: /etc/neb/config
    volumes:
      - "${HOST_PWD:-.}/data:/out"
      - "${HOST_PWD:-.}/config/neb-config:/etc/neb/config:ro"

  bake-book:
    build: .
    image: openstax/cnx-recipes
    environment:
      # This is necessary in order to mount the correct directory if we start
      # sibling containers
      HOST_PWD: "${PWD}"
    volumes:
      - .:/code
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: /code/script/bake-book
